version: '3.8'
services:
  feature_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ONLINE_STORE_PASSWORD=${REDIS_PASSWORD}
      - USER_ID=${USER_ID}
    ports:
      - 8888:8888
      - 6566:6566
    volumes:
      - ./feature_hero_repo:/feature_hero_repo
    depends_on:
      - redis

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    environment:
      - REDISTIMESERIES_ARGS="RETENTION_POLICY=20"
    volumes:
      - redis:/data
    ports:
      - 6379:6379
      - 8001:8001

volumes:
  redis:
      driver: local